### ISSUE TITLE
No test data in the specified folder

### ISSUE THREAD

**Issue by lalithnag** [clausmichele/ViDeNN#2]
Thanks for putting out your trained model! 

I'm trying to denoise a video that I have. I forked-cloned your repo and then I placed my  video in the ../VidCNN---Learning-Blind-Video-Denoising directory and then ran the scrip as follows:

$ sh denoise.sh
VidCNN - Learning Blind Video Denoising
[*] Insert the video file name you want to denoise:
icuts-video-1-suture_left
[*] Extracting frames to the Noisy folder...
ffmpeg version N-92539-g1035206102 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181017
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 24.101 / 56. 24.101
  libavcodec     58. 40.100 / 58. 40.100
  libavformat    58. 23.100 / 58. 23.100
  libavdevice    58.  6.100 / 58.  6.100
  libavfilter     7. 46.100 /  7. 46.100
  libswscale      5.  4.100 /  5.  4.100
  libswresample   3.  4.100 /  3.  4.100
  libpostproc    55.  4.100 / 55.  4.100
./icuts-video-1-suture_left: No such file or directory
[*] Denoising frames, will be stored in ./data/denoised/
GPU

[*] Initialize model successfully...
[!] Folder with original files not found, PSNR values will be WRONG!
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    tf.app.run()
  File "C:\Users\nag\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 38, in main
    vidcnn_test(model)
  File "main.py", line 23, in vidcnn_test
    vidcnn.test(noisy_files, orig_files, ckpt_dir=args.ckpt_dir, save_dir='./data/denoised')
  File "D:\00-code\VidCNN---Learning-Blind-Video-Denoising\model_vidcnn.py", line 48, in test
    assert len(noisy_data) != 0, '[!] No test data in the specified folder! Check that contains an original and noisy folder.'
AssertionError: [!] No test data in the specified folder! Check that contains an original and noisy folder.

I get this assertion error. Do I need to place the file in another folder? Please help me out. Thanks in advance!

**Comment by lalithnag** [comment]
Extremely sorry, I made a mistake in the file name - it seems to be working now. Thanks!
