### ISSUE TITLE
unexpected keyword "labels"

### ISSUE THREAD

**Issue by ajeema** [clausmichele/ViDeNN#36]
Going through the documentation, when I get to running main_temp3CNN.py I get the following errors.

2023-09-27 01:16:46.861651: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-27 01:16:46.911723: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-27 01:16:47.934225: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
GPU

2023-09-27 01:16:51.034872: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2023-09-27 01:16:51.034925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 28359 MB memory:  -> device: 0, name: NVIDIA A100-SXM4-40GB, pci bus id: 0000:00:04.0, compute capability: 8.0
/content/drive/MyDrive/ViDeNN/Temp3-CNN/model_temp3CNN.py:16: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  output = tf.compat.v1.layers.conv2d(input, 128, 3, padding='same', activation=tf.nn.leaky_relu)
/content/drive/MyDrive/ViDeNN/Temp3-CNN/model_temp3CNN.py:19: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  output = tf.compat.v1.layers.conv2d(output, 64, 3, padding='same', name='conv%d' % layers, use_bias=False)
/content/drive/MyDrive/ViDeNN/Temp3-CNN/model_temp3CNN.py:22: UserWarning: `tf.layers.conv2d` is deprecated and will be removed in a future version. Please Use `tf.keras.layers.Conv2D` instead.
  output = tf.compat.v1.layers.conv2d(output, output_channels, 3, padding='same', use_bias=False)
Traceback (most recent call last):
  File "/content/drive/MyDrive/ViDeNN/Temp3-CNN/main_temp3CNN.py", line 96, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/platform/app.py", line 36, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.10/dist-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/content/drive/MyDrive/ViDeNN/Temp3-CNN/main_temp3CNN.py", line 74, in main
    model = TemporalDenoiser(sess)
  File "/content/drive/MyDrive/ViDeNN/Temp3-CNN/model_temp3CNN.py", line 42, in __init__
    self.eva_psnr = tf_psnr(self.Y, self.Y_[:,:,:,3:6])
  File "/content/drive/MyDrive/ViDeNN/Temp3-CNN/utilis.py", line 89, in tf_psnr
    mse = tf.losses.mean_squared_error(labels=im2 * 255.0, predictions=im1 * 255.0)
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/util/dispatch.py", line 1170, in op_dispatch_handler
    result = api_dispatcher.Dispatch(args, kwargs)
TypeError: Got an unexpected keyword argument 'labels'

Everything up until this step worked fine. Any idea what could be the issue?

**Comment by ajeema** [comment]
Found the answer, I had updated the other scripts to tf2 but forgot to update this file. Leaving this here and closing in case anyone else runs into this issue.
